# Notebook for evaluating forecasts

In [5]:
import pandas as pd
from sklearn.metrics import *

In [6]:
# Replace with your csv file name
df_results = pd.read_csv("../Data/Submission/submission_A.csv")
df_results = pd.read_csv("../Data/Submission/submission_B.csv")
df_solution = pd.read_csv("../Data/Solution_A.csv")

In [7]:
df_results

          TIMESTAMP     POWER
0    20180301 01:00  0.657001
1    20180301 02:00  0.659345
2    20180301 03:00  0.609231
3    20180301 04:00  0.587774
4    20180301 05:00  0.437840
..              ...       ...
739  20180331 20:00  0.240542
740  20180331 21:00  0.219732
741  20180331 22:00  0.182684
742  20180331 23:00  0.171498
743  20180401 00:00  0.215366

[744 rows x 2 columns]

In [8]:
df_solution

          TIMESTAMP     POWER
0    20180201 01:00  0.876351
1    20180201 02:00  0.921515
2    20180201 03:00  0.895380
3    20180201 04:00  0.898016
4    20180201 05:00  0.862974
..              ...       ...
667  20180228 20:00  0.666377
668  20180228 21:00  0.665494
669  20180228 22:00  0.740842
670  20180228 23:00  0.699803
671  20180301 00:00  0.710395

[672 rows x 2 columns]

In [9]:
def evaluate_preds(df_own_predictions: pd.DataFrame, df_solution: pd.DataFrame):
    
    format = '%Y%m%d %H:%M'
    
    df_own_predictions['DATETIME'] = pd.to_datetime(df_own_predictions['TIMESTAMP'].astype("string"), format=format)
    df_solution['DATETIME'] = pd.to_datetime(df_solution['TIMESTAMP'].astype("string"), format=format)
    
    df_own_predictions = df_own_predictions.set_index(pd.DatetimeIndex(df_own_predictions['DATETIME']))
    df_solution = df_solution.set_index(pd.DatetimeIndex(df_solution['DATETIME']))
    
    df_own_predictions.sort_index()
    df_solution.sort_index()
    
    assert len(df_own_predictions) == len(df_solution)
    df_len = len(df_own_predictions)
    assert df_own_predictions['DATETIME'][0] == df_solution['DATETIME'][0]
    assert df_own_predictions['DATETIME'][df_len-1] == df_solution['DATETIME'][df_len-1]
    
    preds=[]
    actuals=[]
    for index, values in df_own_predictions.iterrows():
        preds.append(df_own_predictions.loc[[index]]['POWER'][0])
        actuals.append(df_solution.loc[[index]]['POWER'][0])
    score = r2_score(actuals, preds)
    
    print("R2 SCORE: %f" % (score))

In [10]:
evaluate_preds(df_own_predictions=df_results, df_solution=df_solution)

AssertionError: